#!/usr/sbin/nft -f

flush ruleset

table inet filter {

    chain input {
        type filter hook input priority 0;
        policy drop;

        iif lo accept

        ct state established,related accept

        ct state invalid drop

        ip protocol icmp accept
        ip6 nexthdr icmpv6 accept

        udp sport 67 udp dport 68 accept
        udp sport 68 udp dport 67 accept

        iifname "waydroid0" udp dport { 53, 67 } accept
    }

    chain forward {
        type filter hook forward priority 0;
        policy drop;

        ct state established,related accept

        iifname "waydroid0" oifname "wlp3s0" accept
    }

    chain output {
        type filter hook output priority 0;
        policy accept;
    }
}

table ip nat {

    chain POSTROUTING {
        type nat hook postrouting priority 100;
        policy accept;

        oifname "wlp3s0" ip saddr 192.168.240.0/24 masquerade
    }
}
